### ISSUE TITLE
[Home Page] Add homepage camp video

### ISSUE THREAD

**Issue by sloh4137** [TACL-LYF/lyf-website#23]
# Context

The Figma design has an [overlay over the video](https://www.figma.com/file/p3jTW66oX0UTb9uHKXjTFm/LYF-Website-Brainstorm?node-id=739%3A76121&t=XgQ6RPpBLFCzNazD-0) when it's paused

*Estimated Size*: L 

# To-Do

- [ ] Add a YouTube link to the [homePage schema](https://github.com/TACL-LYF/lyf-website-cms/blob/main/schemas/singletons/homePage.ts#L51)
  - Probably something like  https://www.sanity.io/docs/url-type 
- [ ] Pull the url in Gatsby from Sanity [into the homePage](https://github.com/TACL-LYF/lyf-website/blob/main/src/pages/index.tsx#L27)
- [ ] Render the YouTube video
- [ ] Add an overlay to the YouTube video when paused
