### ISSUE TITLE
[Website] Create "Up Next" sections

### ISSUE THREAD

**Issue by sloh4137** [TACL-LYF/lyf-website#27]
*Estimated Size*: L

# To-Do
Some pages on the Figma have a "Up Next" section which links to other pages. We can create some shared components for these 

- [ ] Check if we're sharing this schema in the CMS 
  - [ ] If not, then we definitely can start sharing this. It's pretty similar to the card content 
- [ ] Build an UpNextSection component that take in the photos and content for the sections     
- [ ] Add the Up Next section to relevant pages
  - [ ] May need to add to schemas too
