### ISSUE TITLE
[Website] Add the Cookbook Page

### ISSUE THREAD

**Issue by sloh4137** [TACL-LYF/lyf-website#28]
# Context
Design: https://www.figma.com/file/p3jTW66oX0UTb9uHKXjTFm/LYF-Website-Brainstorm?node-id=994%3A79244&t=XgQ6RPpBLFCzNazD-0

Schema: https://github.com/TACL-LYF/lyf-website-cms/issues/19 

*Estimated Size*: XL

# To-Do
This one is a bit of a woozy to write all out but I see 5 main sections to this page
- [ ] Photo with rotating gallery
- [ ] Header and subheader
- [ ] Collapsible info 
- [ ] Quotes
- [ ] Order with Paypal Button

This issue really could be split up into multiple issues if we wanted to be simpler with our PR changes
